---

extends:
  - airbnb
  - "plugin:jest/recommended"

parser: babel-eslint

env:
  browser: true
  node: true
  jest: true

settings:
  import/resolver: webpack

rules:
  import/extensions: 0
  react/prop-types: 0
